aliases:
  decoration:
    img: &img
      border: 1px
      borderStyle: dashed dashed dashed
    unused: &unused
      border: 0px
sugarcube-2:
  macros:
    abominationold: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<initWraith "abomination">>
    abominationold2: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<initWraith "abomination">>
    actionsanuspenisfuck: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsanuspenisfucknew>>
    actionsanustopenis: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsanustopenis>>
    actionsvaginapenisfuck: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsvaginapenisfuck>>
    actionsvaginatopenis: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsvaginatopenisnew>>
    actionsvaginatovagina: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsvaginatovaginanew>>
    actionsvaginatovaginafuck: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<actionsvaginatovaginafucknew>>
    adultshopicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "adult">>
    animals: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - '?animals'
    bathicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<bathroomicon "bath">>
    bathrobeicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<bathroomicon "robe">>
    beericon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "beer">>
    binicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<icon "bin.png">>
    bloodmirroricon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<mirroricon "blood">>
    bodyparts: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - '?bodypart'
    breastenlargeicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "breast enlarge">>
    breastreduceicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "breast reduce">>
    cellicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "cell">>
    checkTimeSystem: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - Time cannot desync anymore
    chickenicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<animalicon "chicken">>
    clearyardicon:
      deprecated: true
      deprecatedSuggestions:
        - <<farmicon "clear yard">>
    closedstoreicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "closed">>
    clothingShop: # Deprecated 0.4.5+
      deprecated: true
    clothingShopColorSet: # Deprecated 0.4.5+
      deprecated: true
    clothingshopicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "clothing">>
    coffeeicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "coffee">>
    computericon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "computer">>
    condommachineicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<condomicon "machine">>
    contactsicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<cosmeticsicon "contacts">>
    cottageicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<farmicon "cottage">>
    cowicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<animalicon "cow">>
    danubehouseicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<dooricon "danube">>
    dilapidatedshopicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "dilapidated">>
    dogicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<animalicon "dog">>
    domushouseicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<dooricon "domus">>
    dyeicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<cosmeticsicon "dyes">>
    eaticon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "eat">>
    feetgrab: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<feetgrabnew>>
    flatdooricon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<dooricon>>
    flatdooropenicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<dooricon "open">>
    flowericon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<gardenicon "flower">>
    forestroaddeepicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<forestroadicon "deep">>
    forestroadtownicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<forestroadicon "town">>
    forestshopicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "forest">>
    garden: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - '?garden'
    generatec1: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey1>>
    generatec2: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey2>>
    generatec3: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey3>>
    generatec4: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey4>>
    generatec5: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey5>>
    generatec6: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<generatey6>>
    hairchairicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<hairdressericon "chair">>
    hairgelicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<hairdressericon "gel">>
    headdeskicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "headdesk">>
    hitchhikeicon: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<skinicon "hitchhike">>
    homemirroricon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<mirroricon "home">>
    horseicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<animalicon "horse">>
    hotchocicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "cocoa">>
    hotchocstandicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<robinicon "cocoa">>
    humiliation10: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<stress 40 1>><<trauma 1>>
    infirmaryicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "infirmary">>
    lemonadeicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "lemonade">>
    lemonadestandicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<robinicon "lemonade">>
    libraryicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "library">>
    lowerbodyparts: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - '?lowerbodypart'
    masturbationactionsOld: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<masturbationactions>>
    masturbationeffectsOld: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<masturbationeffects>>
    meadowicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<farmicon "meadow">>
    milkshakeicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "milkshake">>
    newversionnotification: # Deprecated 0.4.5+
      deprecated: true
      description: Has been non-functioning for a good while now
    olivenewicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<oliveicon>>
    oralswallow: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<oralswallownew>>
      orphanagedoorsicon: # Deprecated 0.4.3+
        deprecated: true
        deprecatedSuggestions:
          - <<dooricon "orphanage">>
    parasitecreamicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "parasite">>
    partyicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - - <<socialiseicon "party">>
    paternity_test: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "paternity">>
    penisenlargeicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "penis enlarge">>
    penisreduceicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<procedureicon "penis reduce">>
    pigicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<animalicon "pig">>
    plaqueicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "plaque">>
    poollockericon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<lockericon>>
    pregnancyWatersBrokenPassout: # Deprecrated 0.4.6+
      deprecated: true
      deprecatedSuggestions:
        - <<pregnancyPassout>>
    printAnd: # Deprecrated 0.4.5.3+
      deprecated: true
      deprecatedSuggestions:
        - and
      description: |-
        Prints `and` for use where `and` cannot be used without escaping
    printTo: # Deprecrated 0.4.5.3+
      deprecated: true
      deprecatedSuggestions:
        - to
      description: |-
        Prints `to` for use where `to` cannot be used without escaping
    prisoncanteenicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "canteen">>
    prisondooricon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "door">>
    prisonlaundryicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "laundry">>
    prisonlifticon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "lift">>
    prisonmedicalicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "medical">>
    prisonrunicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<prisonicon "run">>
    putinlockericon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<lockericon "put in">>
    registericon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "register">>
    scarletnewicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<scarleticon>>
    schoolbuildingicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "building">>
    schoolcourtyardicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "courtyard">>
    searchicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<icon "search.png">>
    secretpathicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<forestroadicon "secret">>
    shaveicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<bathroomicon "shave">>
    shopbuy: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<shopbuyv2>>
    shopClothingFilterLoadTraits: # Deprecated 0.4.5+
      deprecated: true
    shopClothingFilterSettings: # Deprecated 0.4.5+
      deprecated: true
    shopClothingFilterToggle: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColors: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColorsBars: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColorsDisplay: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColorsPresets: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColorsPresetsLoad: # Deprecated 0.4.5+
      deprecated: true
    shopCustomColorsSet: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - '<<setShopCustomColors>>'
    shopCustomColorsToggle: # Deprecated 0.4.5+
      deprecated: true
    shopDefaultOptions: # Deprecated 0.4.3+
      deprecated: true
    shopDefaultOptionsToggle: # Deprecated 0.4.3+
      deprecated: true
    shoppingcentreicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon>>
    shopTraitDescription: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - 'setup.shopDetails[_trait].desc'
    sizeLimitsSettingsOld: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<sizeLimitsSettings>>
    stairschristmasicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<main_hall_icon>>
    stairsdownicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<stairsicon "down">>
    stairshalloweenicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<main_hall_icon>>
    stairsupicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<stairsicon "up">>
    statbaricons: # Deprecated Old
      deprecated: true
      description: "![img](%workspaceDir%/img/ui/point.png)"
    stripicon: # Deprecated 0.4.5+
      deprecated: true
      deprecatedSuggestions:
        - <<skinicon "strip">>
    stumpicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<schoolicon "stump">>
    sweetsicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<foodicon "halloween">>
        - <<foodicon "sweets">>
    swimbackicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<swimicon "back">>
    tailoricon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "tailor">>
    tattooicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "tattoo">>
    toileticon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<bathroomicon "toilet">>
    toyshopicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<shopicon "toy">>
    updateClothes-obsolete: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<updateClothes>>
    updateClothingColours-obsolete: # Deprecated Old
      deprecated: true
      deprecatedSuggestions:
        - <<updateClothes>>
    venteyesicon: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<venticon "eyes">>
    volleyballicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - - <<socialiseicon "volleyball">>
    wolfpup: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<wolfcaveicon "pup">>
    wolfsleep: # Deprecated 0.4.2+
      deprecated: true
      deprecatedSuggestions:
        - <<wolfcaveicon "sleep">>
    wrenchicon: # Deprecated 0.4.3+
      deprecated: true
      deprecatedSuggestions:
        - <<icon "wrench.png">>
